services:
  fivem:
    image: ghcr.io/wesleymethorst/fivem-enhanced:enhanced
    pull_policy: always
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      TXHOST_GAME_NAME: "fivem"
      TXHOST_TXA_PORT: "40120"
      TXHOST_INTERFACE: "0.0.0.0"
      TXHOST_DATA_PATH: "/txData"
    volumes:
      - /home/fivem/woenselcombat:/txData
    ports:
      - "30120:30120/tcp"
      - "30120:30120/udp"
      - "40120:40120/tcp"
