services:
  fivem:
    build: .
    image: fivem-enhanced:90
    container_name: fivem
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - "/path/to/resources/folder:/config"
      # Enable a volume mount for txAdmin's data files
      # - "/path/to/txData/folder:/txData"
    ports:
      - "30120:30120"
      - "30120:30120/udp"
      # Allow txAdmin's webserver port to be accessible
      # - "40120:40120"
    environment:
      LICENSE_KEY: "license-key-here"





services:
  fivem:
    build: .
    image: ghcr.io/wesleymethorst/fivem-enhanced:sha-c307c40
    restart: unless-stopped
    tty: true
    stdin_open: true

    environment:
      NO_DEFAULT_CONFIG: "1"

    volumes:
      - /home/fivem/woenselcombat:/txData

    ports:
      - "30120:30120/tcp"
      - "30120:30120/udp"
      - "40120:40120"

    labels:
      - "traefik.enable=true"