#!/bin/sh

[ -n "${DEBUG}" ] && set -x

exec /lib/ld-musl-x86_64.so.1 \
    --library-path "/lib/:/usr/lib/" \
    -- \
    /opt/cfx-server/cfx-server \
        +set citizen_dir /opt/cfx-server/citizen/ \
        "$@"
